nome: Imprime data atual

em:
  empurrar:
  
empregos:
  imprime_data_ubuntu:
    nome: Imprime data atual - Ubuntu
    runs-on: ubuntu-mais recente
    
    passos:
      - nome: Imprime data atual
        executar: data
  
  imprime_data_windows:
    nome: Imprime data atual - Windows
    runs-on: windows-latest
    
    passos:
      - nome: Imprime data atual
        executar: data
        
  imprime_data_macos:
    nome: Imprime data atual - MacOS
    runs-on: macos-mais recente
    
    passos:
      - nome: Imprime data atual
        executar: data
        
  imprime_data_final:
    nome: Imprimir dados - trabalho final
    runs-on: ubuntu-mais recente
    necessidades: [imprime_data_ubuntu, imprime_data_windows, imprime_data_macos]
    
    passos:
      - nome: Imprime data atual
        executar: data
